### ISSUE TITLE
Running SEED.rb errors out both on heroku-cli and locally

### ISSUE THREAD

**Issue by streaak** [salesforce/vulnreport#27]
Here's the paste from heroku-cli-
```
root@ubuntu:/home/streaak/github/vulnreport# heroku run ./SEED.rb -a vulnreport-streaak
Running ./SEED.rb on ⬢ vulnreport-streaak... up, run.4968 (Free)
bash: ./SEED.rb: No such file or directory
root@ubuntu:/home/streaak/github/vulnreport# 
```

Here's the paste trying to run it locally-
```
root@ubuntu:/home/streaak/github/vulnreport# ./SEED.rb 


Vulnreport 3.0.3 seed script
WARNING: This script should be run ONCE immediately after deploying and then DELETED

Setting up Vulnreport now...

Setting up the PostgreSQL database...
Traceback (most recent call last):
	5: from ./SEED.rb:21:in `<main>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /home/streaak/github/vulnreport/models/init.rb:9:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- data_mapper (LoadError)
root@ubuntu:/home/streaak/github/vulnreport# 
```

Please advice on what to do. Thanks.

**Comment by littledatas** [comment]
Have you run a `bundle install` to install the gems? It appears that you do not have the datamapper gem installed.

**Comment by streaak** [comment]
Hey,
I tried running that now and got the following error-
`Your Ruby version is 2.5.1, but your Gemfile specified 2.1.2`
So I edited the Gemfile to have `ruby '2.5.1'` ( Not sure if this was the cause for the following error)
Now I got the following error-
```
root@ubuntu:/home/streaak/github/vulnreport# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/...............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching json 1.8.3
Installing json 1.8.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/json-1.8.3/ext/json/ext/generator
/usr/bin/ruby2.5 -r ./siteconf20180612-4929-635vqx.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /var/lib/gems/2.5.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function); did you mean ‘mFixnum’?
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
                         mFixnum
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function); did you mean ‘rb_cFixnum’?
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
                         rb_cFixnum
Makefile:242: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.5.0/gems/json-1.8.3 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  activesupport was resolved to 4.2.6, which depends on
    json
root@ubuntu:/home/streaak/github/vulnreport#
```

**Comment by littledatas** [comment]
I would install rvm (https://rvm.io/rvm/basics) to install ruby version 2.1.2. I won't be able to help much with troubleshooting issues not on that ruby version. We are working internally to get the ruby version updated but will take some time.

I would look at the json gem project because its an issue with that dependency. Here's an issue on that project which may help you troubleshoot some steps (https://github.com/flori/json/issues/253)

**Comment by littledatas** [comment]
I am going to go ahead and close this since I haven't heard anything in about 2 weeks. Please feel free to re-open if you are still running into issues.
