### ISSUE TITLE
SEED.rb fails

### ISSUE THREAD

**Issue by SecurityAmoeba** [salesforce/vulnreport#9]
Installation instructions have been followed, seemingly all required files/gems etc are present. Running ./SEED.rb produces:

    Setting up Vulnreport now...

    Setting up the PostgreSQL database...
    /home/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- dm--adapter (LoadError)
	from /home/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /home/dev/.rvm/gems/ruby-2.1.2/gems/dm-core-1.2.1/lib/dm-core/adapters.rb:163:in `load_adapter'
	from /home/dev/.rvm/gems/ruby-2.1.2/gems/dm-core-1.2.1/lib/dm-core/adapters.rb:133:in `adapter_class'
	from /home/dev/.rvm/gems/ruby-2.1.2/gems/dm-core-1.2.1/lib/dm-core/adapters.rb:13:in `new'
	from /home/dev/.rvm/gems/ruby-2.1.2/gems/dm-core-1.2.1/lib/dm-core.rb:230:in `setup'
	from /home/dev/vulnreport/models/init.rb:19:in `<top (required)>'
	from /home/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./SEED.rb:20:in `<main>'

**Comment by SecurityAmoeba** [comment]
I am an idiot. I was thinking that the creation of a database would be scripted. Read through documentation + https://github.com/salesforce/vulnreport/issues/5 and realized my mistake. Apologies! Great app by the way!
